// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package server

import (
	"context"

	"lookingforpartner/pb/user"
	"lookingforpartner/service/user/rpc/internal/logic"
	"lookingforpartner/service/user/rpc/internal/svc"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) WxLogin(ctx context.Context, in *user.WxLoginRequest) (*user.WxLoginResponse, error) {
	l := logic.NewWxLoginLogic(ctx, s.svcCtx)
	return l.WxLogin(in)
}

func (s *UserServer) SetUserInfo(ctx context.Context, in *user.SetUserInfoRequest) (*user.SetUserInfoResponse, error) {
	l := logic.NewSetUserInfoLogic(ctx, s.svcCtx)
	return l.SetUserInfo(in)
}

func (s *UserServer) GetUserInfo(ctx context.Context, in *user.GetUserInfoRequest) (*user.GetUserInfoResponse, error) {
	l := logic.NewGetUserInfoLogic(ctx, s.svcCtx)
	return l.GetUserInfo(in)
}

func (s *UserServer) UpdateUserPostCount(ctx context.Context, in *user.UpdateUserPostCountRequest) (*user.UpdateUserPostCountResponse, error) {
	l := logic.NewUpdateUserPostCountLogic(ctx, s.svcCtx)
	return l.UpdateUserPostCount(in)
}
