// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package server

import (
	"context"

	"lookingforpartner/service/user/rpc/internal/logic"
	"lookingforpartner/service/user/rpc/internal/svc"
	"lookingforpartner/service/user/rpc/pb/user"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) WxLogin(ctx context.Context, in *user.WxLoginRequest) (*user.WxLoginResponse, error) {
	l := logic.NewWxLoginLogic(ctx, s.svcCtx)
	return l.WxLogin(in)
}

func (s *UserServer) SetUserBaseInfo(ctx context.Context, in *user.SetUserBaseInfoRequest) (*user.SetUserBaseInfoResponse, error) {
	l := logic.NewSetUserBaseInfoLogic(ctx, s.svcCtx)
	return l.SetUserBaseInfo(in)
}

func (s *UserServer) GetUserBaseInfo(ctx context.Context, in *user.GetUserBaseInfoRequest) (*user.GetUserBaseInfoResponse, error) {
	l := logic.NewGetUserBaseInfoLogic(ctx, s.svcCtx)
	return l.GetUserBaseInfo(in)
}

func (s *UserServer) SetUserExtraInfo(ctx context.Context, in *user.SetUserExtraInfoRequest) (*user.SetUserExtraInfoRequest, error) {
	l := logic.NewSetUserExtraInfoLogic(ctx, s.svcCtx)
	return l.SetUserExtraInfo(in)
}

func (s *UserServer) GetUserExtraInfo(ctx context.Context, in *user.GetUserExtraInfoRequest) (*user.GetUserExtraInfoRequest, error) {
	l := logic.NewGetUserExtraInfoLogic(ctx, s.svcCtx)
	return l.GetUserExtraInfo(in)
}
