// Code generated by goctl. DO NOT EDIT.
package types

type CreatePostRequest struct {
	Title   string  `json:"title"`
	Project Project `json:"project"`
	Content string  `json:"content"`
}

type CreatePostResponse struct {
	Post Post `json:"post"`
}

type DeletePostRequest struct {
	PostID string `path:"postID"`
}

type DeletePostResponse struct {
}

type GetPostByAuthorIDRequest struct {
	AuthorID string `path:"authorID"`
	PaginationParams
}

type GetPostRequest struct {
	PostID string `path:"postID"`
}

type GetPostResponse struct {
	Post Post `json:"post"`
}

type GetPostsByAuthorIDResponse struct {
	Posts     []Post    `json:"posts"`
	Paginator Paginator `json:"paginator"`
}

type GetPostsRequest struct {
	PaginationParams
}

type GetPostsResponse struct {
	Posts     []Post    `json:"posts"`
	Paginator Paginator `json:"paginator"`
}

type PaginationParams struct {
	Page  int64  `path:"page"`
	Size  int64  `path:"size"`
	Order string `path:"order"`
}

type Paginator struct {
	TotalRecord int64 `json:"total_record"`
	TotalPage   int   `json:"total_page"`
	Offset      int   `json:"offset"`
	Limit       int   `json:"limit"`
	CurrPage    int   `json:"curr_page"`
	PrevPage    int   `json:"prev_page"`
	NextPage    int   `json:"next_page"`
}

type Post struct {
	PostID    string  `json:"post_id"`
	CreatedAt string  `json:"created_at"`
	Title     string  `json:"title"`
	Project   Project `json:"project"`
	Content   string  `json:"content"`
	AuthorID  string  `json:"author_id"`
}

type Project struct {
	ProjectID     string   `json:"project_id"`
	Name          string   `json:"name"`
	Introduction  string   `json:"introduction"`
	Maintainer    UserInfo `json:"maintainer"`
	Role          string   `json:"role"`
	HeadCountInfo string   `json:"head_count_info"`
	Progress      string   `json:"progress"`
}

type UpdateProjectRequest struct {
	ProjectID      string         `path:"projectID"`
	UpdatedProject UpdatedProject `json:"updated_project"`
}

type UpdateProjectResponse struct {
	Project Project `json:"project"`
}

type UpdatedProject struct {
	Name          string `json:"name"`
	Introduction  string `json:"introduction"`
	Role          string `json:"role"`
	HeadCountInfo string `json:"head_count_info"`
	Progress      string `json:"progress"`
}

type UserInfo struct {
	WxUid        string `json:"wx_uid"`
	Avatar       string `json:"avatar"`
	School       string `json:"school"`
	Grade        int64  `json:"grade"`
	Introduction string `json:"introduction"`
	PostCount    int64  `json:"post_count"`
	Username     string `json:"username"`
}
