// Code generated by goctl. DO NOT EDIT.
// Source: leaf.proto

package leafclient

import (
	"context"

	"lookingforpartner/pb/leaf"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	NextSegmentRequest  = leaf.NextSegmentRequest
	NextSegmentResponse = leaf.NextSegmentResponse

	Leaf interface {
		NextSegment(ctx context.Context, in *NextSegmentRequest, opts ...grpc.CallOption) (*NextSegmentResponse, error)
	}

	defaultLeaf struct {
		cli zrpc.Client
	}
)

func NewLeaf(cli zrpc.Client) Leaf {
	return &defaultLeaf{
		cli: cli,
	}
}

func (m *defaultLeaf) NextSegment(ctx context.Context, in *NextSegmentRequest, opts ...grpc.CallOption) (*NextSegmentResponse, error) {
	client := leaf.NewLeafClient(m.cli.Conn())
	return client.NextSegment(ctx, in, opts...)
}
