// Code generated by goctl. DO NOT EDIT.
package types

type GetUserBaseInfoRequest struct {
}

type GetUserBaseInfoResponse struct {
	Avatar string `json:"avatar"`
	School string `json:"school"`
	Grade  int    `json:"grade"`
}

type GetUserExtraInfoRequest struct {
}

type GetUserExtraInfoResponse struct {
	Introduction string `json:"introduction"`
	PostCount    int    `json:"post_count"`
}

type RefreshTokenReqeust struct {
}

type RefreshTokenResponse struct {
	Token        string `json:"token"`
	RefreshToken string `json:"refresh_token"`
}

type SetUserBaseInfoRequest struct {
	School string `json:"school"`
	Grade  int    `json:"grade"`
}

type SetUserBaseInfoResponse struct {
}

type SetUserExtraInfoRequest struct {
	Introduction string `json:"introduction"`
}

type SetUserExtraInfoResponse struct {
}

type UserInfo struct {
	WxUid        string `json:"wx_uid"`
	Avatar       string `json:"avatar"`
	School       string `json:"school"`
	Grade        int    `json:"grade"`
	Introduction string `json:"introduction"`
	PostCount    int    `json:"post_count"`
	Username     string `json:"username"`
}

type WxLoginRequest struct {
	Code string `json:"code"`
}

type WxLoginResponse struct {
	Token        string   `json:"token"`
	RefreshToken string   `json:"refresh_token"`
	UserInfo     UserInfo `json:"user_info"`
}
