// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v3.19.4
// source: leaf/leaf.proto

package leaf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// NextSegment
type NextSegmentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BizTag string `protobuf:"bytes,1,opt,name=BizTag,proto3" json:"BizTag,omitempty"`
	Step   int64  `protobuf:"varint,2,opt,name=Step,proto3" json:"Step,omitempty"`
}

func (x *NextSegmentRequest) Reset() {
	*x = NextSegmentRequest{}
	mi := &file_leaf_leaf_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NextSegmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NextSegmentRequest) ProtoMessage() {}

func (x *NextSegmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_leaf_leaf_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NextSegmentRequest.ProtoReflect.Descriptor instead.
func (*NextSegmentRequest) Descriptor() ([]byte, []int) {
	return file_leaf_leaf_proto_rawDescGZIP(), []int{0}
}

func (x *NextSegmentRequest) GetBizTag() string {
	if x != nil {
		return x.BizTag
	}
	return ""
}

func (x *NextSegmentRequest) GetStep() int64 {
	if x != nil {
		return x.Step
	}
	return 0
}

type NextSegmentResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FirstID int64 `protobuf:"varint,1,opt,name=FirstID,proto3" json:"FirstID,omitempty"`
	LastID  int64 `protobuf:"varint,2,opt,name=LastID,proto3" json:"LastID,omitempty"`
}

func (x *NextSegmentResponse) Reset() {
	*x = NextSegmentResponse{}
	mi := &file_leaf_leaf_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NextSegmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NextSegmentResponse) ProtoMessage() {}

func (x *NextSegmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_leaf_leaf_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NextSegmentResponse.ProtoReflect.Descriptor instead.
func (*NextSegmentResponse) Descriptor() ([]byte, []int) {
	return file_leaf_leaf_proto_rawDescGZIP(), []int{1}
}

func (x *NextSegmentResponse) GetFirstID() int64 {
	if x != nil {
		return x.FirstID
	}
	return 0
}

func (x *NextSegmentResponse) GetLastID() int64 {
	if x != nil {
		return x.LastID
	}
	return 0
}

var File_leaf_leaf_proto protoreflect.FileDescriptor

var file_leaf_leaf_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x6c, 0x65, 0x61, 0x66, 0x2f, 0x6c, 0x65, 0x61, 0x66, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0a, 0x6c, 0x65, 0x61, 0x66, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x22, 0x40, 0x0a,
	0x12, 0x4e, 0x65, 0x78, 0x74, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x42, 0x69, 0x7a, 0x54, 0x61, 0x67, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x42, 0x69, 0x7a, 0x54, 0x61, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x53,
	0x74, 0x65, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x53, 0x74, 0x65, 0x70, 0x22,
	0x47, 0x0a, 0x13, 0x4e, 0x65, 0x78, 0x74, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x46, 0x69, 0x72, 0x73, 0x74, 0x49,
	0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x46, 0x69, 0x72, 0x73, 0x74, 0x49, 0x44,
	0x12, 0x16, 0x0a, 0x06, 0x4c, 0x61, 0x73, 0x74, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x06, 0x4c, 0x61, 0x73, 0x74, 0x49, 0x44, 0x32, 0x56, 0x0a, 0x04, 0x4c, 0x65, 0x61, 0x66,
	0x12, 0x4e, 0x0a, 0x0b, 0x4e, 0x65, 0x78, 0x74, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x12,
	0x1e, 0x2e, 0x6c, 0x65, 0x61, 0x66, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x4e, 0x65, 0x78,
	0x74, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1f, 0x2e, 0x6c, 0x65, 0x61, 0x66, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x4e, 0x65, 0x78,
	0x74, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x42, 0x1b, 0x5a, 0x19, 0x6c, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x66, 0x6f, 0x72, 0x70, 0x61,
	0x72, 0x74, 0x6e, 0x65, 0x72, 0x2f, 0x70, 0x62, 0x2f, 0x6c, 0x65, 0x61, 0x66, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_leaf_leaf_proto_rawDescOnce sync.Once
	file_leaf_leaf_proto_rawDescData = file_leaf_leaf_proto_rawDesc
)

func file_leaf_leaf_proto_rawDescGZIP() []byte {
	file_leaf_leaf_proto_rawDescOnce.Do(func() {
		file_leaf_leaf_proto_rawDescData = protoimpl.X.CompressGZIP(file_leaf_leaf_proto_rawDescData)
	})
	return file_leaf_leaf_proto_rawDescData
}

var file_leaf_leaf_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_leaf_leaf_proto_goTypes = []any{
	(*NextSegmentRequest)(nil),  // 0: leafclient.NextSegmentRequest
	(*NextSegmentResponse)(nil), // 1: leafclient.NextSegmentResponse
}
var file_leaf_leaf_proto_depIdxs = []int32{
	0, // 0: leafclient.Leaf.NextSegment:input_type -> leafclient.NextSegmentRequest
	1, // 1: leafclient.Leaf.NextSegment:output_type -> leafclient.NextSegmentResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_leaf_leaf_proto_init() }
func file_leaf_leaf_proto_init() {
	if File_leaf_leaf_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_leaf_leaf_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_leaf_leaf_proto_goTypes,
		DependencyIndexes: file_leaf_leaf_proto_depIdxs,
		MessageInfos:      file_leaf_leaf_proto_msgTypes,
	}.Build()
	File_leaf_leaf_proto = out.File
	file_leaf_leaf_proto_rawDesc = nil
	file_leaf_leaf_proto_goTypes = nil
	file_leaf_leaf_proto_depIdxs = nil
}
