// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.4
// source: leaf/leaf.proto

package leaf

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Leaf_NextSegment_FullMethodName = "/leafclient.Leaf/NextSegment"
)

// LeafClient is the client API for Leaf service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LeafClient interface {
	NextSegment(ctx context.Context, in *NextSegmentRequest, opts ...grpc.CallOption) (*NextSegmentResponse, error)
}

type leafClient struct {
	cc grpc.ClientConnInterface
}

func NewLeafClient(cc grpc.ClientConnInterface) LeafClient {
	return &leafClient{cc}
}

func (c *leafClient) NextSegment(ctx context.Context, in *NextSegmentRequest, opts ...grpc.CallOption) (*NextSegmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NextSegmentResponse)
	err := c.cc.Invoke(ctx, Leaf_NextSegment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LeafServer is the server API for Leaf service.
// All implementations must embed UnimplementedLeafServer
// for forward compatibility.
type LeafServer interface {
	NextSegment(context.Context, *NextSegmentRequest) (*NextSegmentResponse, error)
	mustEmbedUnimplementedLeafServer()
}

// UnimplementedLeafServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLeafServer struct{}

func (UnimplementedLeafServer) NextSegment(context.Context, *NextSegmentRequest) (*NextSegmentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NextSegment not implemented")
}
func (UnimplementedLeafServer) mustEmbedUnimplementedLeafServer() {}
func (UnimplementedLeafServer) testEmbeddedByValue()              {}

// UnsafeLeafServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LeafServer will
// result in compilation errors.
type UnsafeLeafServer interface {
	mustEmbedUnimplementedLeafServer()
}

func RegisterLeafServer(s grpc.ServiceRegistrar, srv LeafServer) {
	// If the following call pancis, it indicates UnimplementedLeafServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Leaf_ServiceDesc, srv)
}

func _Leaf_NextSegment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NextSegmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeafServer).NextSegment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Leaf_NextSegment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeafServer).NextSegment(ctx, req.(*NextSegmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Leaf_ServiceDesc is the grpc.ServiceDesc for Leaf service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Leaf_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "leafclient.Leaf",
	HandlerType: (*LeafServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NextSegment",
			Handler:    _Leaf_NextSegment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "leaf/leaf.proto",
}
