// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package userclient

import (
	"context"

	"lookingforpartner/service/user/rpc/pb/user"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetUserBaseInfoRequest   = user.GetUserBaseInfoRequest
	GetUserBaseInfoResponse  = user.GetUserBaseInfoResponse
	GetUserExtraInfoRequest  = user.GetUserExtraInfoRequest
	GetUserExtraInfoResponse = user.GetUserExtraInfoResponse
	SetUserBaseInfoRequest   = user.SetUserBaseInfoRequest
	SetUserBaseInfoResponse  = user.SetUserBaseInfoResponse
	SetUserExtraInfoRequest  = user.SetUserExtraInfoRequest
	SetUserExtraInfoResponse = user.SetUserExtraInfoResponse
	UserInfo                 = user.UserInfo
	WxLoginRequest           = user.WxLoginRequest
	WxLoginResponse          = user.WxLoginResponse

	User interface {
		WxLogin(ctx context.Context, in *WxLoginRequest, opts ...grpc.CallOption) (*WxLoginResponse, error)
		SetUserBaseInfo(ctx context.Context, in *SetUserBaseInfoRequest, opts ...grpc.CallOption) (*SetUserBaseInfoResponse, error)
		GetUserBaseInfo(ctx context.Context, in *GetUserBaseInfoRequest, opts ...grpc.CallOption) (*GetUserBaseInfoResponse, error)
		SetUserExtraInfo(ctx context.Context, in *SetUserExtraInfoRequest, opts ...grpc.CallOption) (*SetUserExtraInfoRequest, error)
		GetUserExtraInfo(ctx context.Context, in *GetUserExtraInfoRequest, opts ...grpc.CallOption) (*GetUserExtraInfoRequest, error)
	}

	defaultUser struct {
		cli zrpc.Client
	}
)

func NewUser(cli zrpc.Client) User {
	return &defaultUser{
		cli: cli,
	}
}

func (m *defaultUser) WxLogin(ctx context.Context, in *WxLoginRequest, opts ...grpc.CallOption) (*WxLoginResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.WxLogin(ctx, in, opts...)
}

func (m *defaultUser) SetUserBaseInfo(ctx context.Context, in *SetUserBaseInfoRequest, opts ...grpc.CallOption) (*SetUserBaseInfoResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.SetUserBaseInfo(ctx, in, opts...)
}

func (m *defaultUser) GetUserBaseInfo(ctx context.Context, in *GetUserBaseInfoRequest, opts ...grpc.CallOption) (*GetUserBaseInfoResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.GetUserBaseInfo(ctx, in, opts...)
}

func (m *defaultUser) SetUserExtraInfo(ctx context.Context, in *SetUserExtraInfoRequest, opts ...grpc.CallOption) (*SetUserExtraInfoRequest, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.SetUserExtraInfo(ctx, in, opts...)
}

func (m *defaultUser) GetUserExtraInfo(ctx context.Context, in *GetUserExtraInfoRequest, opts ...grpc.CallOption) (*GetUserExtraInfoRequest, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.GetUserExtraInfo(ctx, in, opts...)
}
