// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package user

import (
	"context"

	"lookingforpartner/service/user/rpc/pb/1user"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetUserInfoRequest  = _1user.GetUserInfoRequest
	GetUserInfoResponse = _1user.GetUserInfoResponse
	SetUserInfoRequest  = _1user.SetUserInfoRequest
	SetUserInfoResponse = _1user.SetUserInfoResponse
	UserInfo            = _1user.UserInfo
	WxLoginRequest      = _1user.WxLoginRequest
	WxLoginResponse     = _1user.WxLoginResponse

	User interface {
		WxLogin(ctx context.Context, in *WxLoginRequest, opts ...grpc.CallOption) (*WxLoginResponse, error)
		SetUserInfo(ctx context.Context, in *SetUserInfoRequest, opts ...grpc.CallOption) (*SetUserInfoResponse, error)
		GetUserInfo(ctx context.Context, in *GetUserInfoRequest, opts ...grpc.CallOption) (*GetUserInfoResponse, error)
	}

	defaultUser struct {
		cli zrpc.Client
	}
)

func NewUser(cli zrpc.Client) User {
	return &defaultUser{
		cli: cli,
	}
}

func (m *defaultUser) WxLogin(ctx context.Context, in *WxLoginRequest, opts ...grpc.CallOption) (*WxLoginResponse, error) {
	client := _1user.NewUserClient(m.cli.Conn())
	return client.WxLogin(ctx, in, opts...)
}

func (m *defaultUser) SetUserInfo(ctx context.Context, in *SetUserInfoRequest, opts ...grpc.CallOption) (*SetUserInfoResponse, error) {
	client := _1user.NewUserClient(m.cli.Conn())
	return client.SetUserInfo(ctx, in, opts...)
}

func (m *defaultUser) GetUserInfo(ctx context.Context, in *GetUserInfoRequest, opts ...grpc.CallOption) (*GetUserInfoResponse, error) {
	client := _1user.NewUserClient(m.cli.Conn())
	return client.GetUserInfo(ctx, in, opts...)
}
