// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"lookingforpartner/service/user/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/info/:id",
				Handler: GetUserInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/wxlogin",
				Handler: WxLoginHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/users"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/info/:id",
				Handler: SetUserInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/refreshtoken",
				Handler: RefreshTokenHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/users"),
	)
}
