// Code generated by goctl. DO NOT EDIT.
// Source: comment.proto

package commentclient

import (
	"context"

	"lookingforpartner/pb/comment"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CommentInfo                 = comment.CommentInfo
	CreateCommentRequest        = comment.CreateCommentRequest
	CreateCommentResponse       = comment.CreateCommentResponse
	CreateSubjectRequest        = comment.CreateSubjectRequest
	CreateSubjectResponse       = comment.CreateSubjectResponse
	DeleteCommentRequest        = comment.DeleteCommentRequest
	DeleteCommentResponse       = comment.DeleteCommentResponse
	GetCommentRequest           = comment.GetCommentRequest
	GetCommentResponse          = comment.GetCommentResponse
	GetCommentsByPostIDRequest  = comment.GetCommentsByPostIDRequest
	GetCommentsByPostIDResponse = comment.GetCommentsByPostIDResponse
	GetSubjectRequest           = comment.GetSubjectRequest
	GetSubjectResponse          = comment.GetSubjectResponse
	SubjectInfo                 = comment.SubjectInfo

	Comment interface {
	}

	defaultComment struct {
		cli zrpc.Client
	}
)

func NewComment(cli zrpc.Client) Comment {
	return &defaultComment{
		cli: cli,
	}
}
