// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.19.1
// source: user.proto

package user

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	User_WxLogin_FullMethodName          = "/userclient.User/WxLogin"
	User_SetUserBaseInfo_FullMethodName  = "/userclient.User/SetUserBaseInfo"
	User_GetUserBaseInfo_FullMethodName  = "/userclient.User/GetUserBaseInfo"
	User_SetUserExtraInfo_FullMethodName = "/userclient.User/SetUserExtraInfo"
	User_GetUserExtraInfo_FullMethodName = "/userclient.User/GetUserExtraInfo"
)

// UserClient is the client API for User service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserClient interface {
	WxLogin(ctx context.Context, in *WxLoginRequest, opts ...grpc.CallOption) (*WxLoginResponse, error)
	SetUserBaseInfo(ctx context.Context, in *SetUserBaseInfoRequest, opts ...grpc.CallOption) (*SetUserBaseInfoResponse, error)
	GetUserBaseInfo(ctx context.Context, in *GetUserBaseInfoRequest, opts ...grpc.CallOption) (*GetUserBaseInfoResponse, error)
	SetUserExtraInfo(ctx context.Context, in *SetUserExtraInfoRequest, opts ...grpc.CallOption) (*SetUserExtraInfoRequest, error)
	GetUserExtraInfo(ctx context.Context, in *GetUserExtraInfoRequest, opts ...grpc.CallOption) (*GetUserExtraInfoRequest, error)
}

type userClient struct {
	cc grpc.ClientConnInterface
}

func NewUserClient(cc grpc.ClientConnInterface) UserClient {
	return &userClient{cc}
}

func (c *userClient) WxLogin(ctx context.Context, in *WxLoginRequest, opts ...grpc.CallOption) (*WxLoginResponse, error) {
	out := new(WxLoginResponse)
	err := c.cc.Invoke(ctx, User_WxLogin_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) SetUserBaseInfo(ctx context.Context, in *SetUserBaseInfoRequest, opts ...grpc.CallOption) (*SetUserBaseInfoResponse, error) {
	out := new(SetUserBaseInfoResponse)
	err := c.cc.Invoke(ctx, User_SetUserBaseInfo_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) GetUserBaseInfo(ctx context.Context, in *GetUserBaseInfoRequest, opts ...grpc.CallOption) (*GetUserBaseInfoResponse, error) {
	out := new(GetUserBaseInfoResponse)
	err := c.cc.Invoke(ctx, User_GetUserBaseInfo_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) SetUserExtraInfo(ctx context.Context, in *SetUserExtraInfoRequest, opts ...grpc.CallOption) (*SetUserExtraInfoRequest, error) {
	out := new(SetUserExtraInfoRequest)
	err := c.cc.Invoke(ctx, User_SetUserExtraInfo_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) GetUserExtraInfo(ctx context.Context, in *GetUserExtraInfoRequest, opts ...grpc.CallOption) (*GetUserExtraInfoRequest, error) {
	out := new(GetUserExtraInfoRequest)
	err := c.cc.Invoke(ctx, User_GetUserExtraInfo_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServer is the server API for User service.
// All implementations must embed UnimplementedUserServer
// for forward compatibility
type UserServer interface {
	WxLogin(context.Context, *WxLoginRequest) (*WxLoginResponse, error)
	SetUserBaseInfo(context.Context, *SetUserBaseInfoRequest) (*SetUserBaseInfoResponse, error)
	GetUserBaseInfo(context.Context, *GetUserBaseInfoRequest) (*GetUserBaseInfoResponse, error)
	SetUserExtraInfo(context.Context, *SetUserExtraInfoRequest) (*SetUserExtraInfoRequest, error)
	GetUserExtraInfo(context.Context, *GetUserExtraInfoRequest) (*GetUserExtraInfoRequest, error)
	mustEmbedUnimplementedUserServer()
}

// UnimplementedUserServer must be embedded to have forward compatible implementations.
type UnimplementedUserServer struct {
}

func (UnimplementedUserServer) WxLogin(context.Context, *WxLoginRequest) (*WxLoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WxLogin not implemented")
}
func (UnimplementedUserServer) SetUserBaseInfo(context.Context, *SetUserBaseInfoRequest) (*SetUserBaseInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetUserBaseInfo not implemented")
}
func (UnimplementedUserServer) GetUserBaseInfo(context.Context, *GetUserBaseInfoRequest) (*GetUserBaseInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserBaseInfo not implemented")
}
func (UnimplementedUserServer) SetUserExtraInfo(context.Context, *SetUserExtraInfoRequest) (*SetUserExtraInfoRequest, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetUserExtraInfo not implemented")
}
func (UnimplementedUserServer) GetUserExtraInfo(context.Context, *GetUserExtraInfoRequest) (*GetUserExtraInfoRequest, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserExtraInfo not implemented")
}
func (UnimplementedUserServer) mustEmbedUnimplementedUserServer() {}

// UnsafeUserServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserServer will
// result in compilation errors.
type UnsafeUserServer interface {
	mustEmbedUnimplementedUserServer()
}

func RegisterUserServer(s grpc.ServiceRegistrar, srv UserServer) {
	s.RegisterService(&User_ServiceDesc, srv)
}

func _User_WxLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WxLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).WxLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_WxLogin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).WxLogin(ctx, req.(*WxLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_SetUserBaseInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetUserBaseInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).SetUserBaseInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_SetUserBaseInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).SetUserBaseInfo(ctx, req.(*SetUserBaseInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_GetUserBaseInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserBaseInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).GetUserBaseInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_GetUserBaseInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).GetUserBaseInfo(ctx, req.(*GetUserBaseInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_SetUserExtraInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetUserExtraInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).SetUserExtraInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_SetUserExtraInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).SetUserExtraInfo(ctx, req.(*SetUserExtraInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_GetUserExtraInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserExtraInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).GetUserExtraInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_GetUserExtraInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).GetUserExtraInfo(ctx, req.(*GetUserExtraInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// User_ServiceDesc is the grpc.ServiceDesc for User service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var User_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "userclient.User",
	HandlerType: (*UserServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "WxLogin",
			Handler:    _User_WxLogin_Handler,
		},
		{
			MethodName: "SetUserBaseInfo",
			Handler:    _User_SetUserBaseInfo_Handler,
		},
		{
			MethodName: "GetUserBaseInfo",
			Handler:    _User_GetUserBaseInfo_Handler,
		},
		{
			MethodName: "SetUserExtraInfo",
			Handler:    _User_SetUserExtraInfo_Handler,
		},
		{
			MethodName: "GetUserExtraInfo",
			Handler:    _User_GetUserExtraInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}
